### ISSUE TITLE
DataCap Roadmap 2024

### ISSUE THREAD

**Issue by qianmoQ** [EdurtIO/incubator-datacap#692]
### Core & Server & Web

---

##### Server

- [ ] Support HA
- [x] Provide Open API
- [x] Support docker composer

##### DataSet

- [x] Support custom life cycle
- [x] Support dynamically adding columns
- [x] Support virtual columns
- [ ] Support pivot data

##### Visual

- [x] Provide more complete chart configuration
- [x] Provide more charts

### Plugin & Scheduler & File System & Source

---

##### Scheduler

- [ ] Support nifi
- [ ] Support streamsets
- [ ] Support kettle
- [ ] Support datax
- [ ] Support Taier
- [ ] Support PowerJob
- [ ] Support Airflow
- [ ] Support Oozie
- [ ] Support xxl-job
- [ ] Support DolphinScheduler 

##### File System

- [ ] Support SeaweedFS
- [ ] Support JuiceFS
- [x] Support lakefs
- [x] Support amazon s3
- [x] Support minio
- [x] Support tencent cos 
- [x] Support aliyun oss
- [x] Support Qiniu cloud storage 

##### Source

- [ ] Support restful api
- [x] Support InfluxDB
- [ ] Support milvus
- [x] Support solr

### Sql Parser & Monitor & Notify

---

##### Sql Parser

- [x] Improve Trino parser
- [x] Improve MySQL parser
- [ ] Support ClickHouse Parser

##### Monitor

- [ ] Support MySQL
- [ ] Support ClickHouse

##### Notify

- [ ] #773
- [x] #772
- [ ] #774

##### UI

- [x] Refactor ui to `shadcn ui`
